# Generated by Django 4.1.6 on 2023-02-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=50)),
                ("real_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("description", models.TextField()),
            ],
        ),
    ]
